#!/usr/bin/env python3
"""Normalize a Figma variables export into design-tokens.json and site-tokens.css.

Usage: normalize_design_system.py <figma-variables.json> <out-dir>

Only reads what is in the export. Anything missing (radii, shadows, breakpoints)
is reported, never invented. Assumptions are listed in the tokens file under "notes".
"""
import json, re, sys, pathlib

WEIGHTS = {"regular": 400, "medium": 500, "semi-bold": 600, "bold": 700}
MOBILE_MAX = 767  # ASSUMPTION: the export has no breakpoint token.


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")


def hexcolor(c):
    h = "#%02x%02x%02x" % tuple(round(c[k] * 255) for k in "rgb")
    return h if c.get("a", 1) == 1 else h + "%02x" % round(c["a"] * 255)


def main(src, out):
    d = json.load(open(src))
    mode = next(iter(d["modes"]))
    tokens = {"color": {}, "spacing": {}, "font": {}, "weight": {},
              "size": {"desktop": {}, "mobile": {}},
              "lineHeight": {"desktop": {}, "mobile": {}},
              "letterSpacing": {"desktop": {}, "mobile": {}}}
    notes = []
    for v in d["variables"]:
        val = v["valuesByMode"][mode]
        parts = [p.strip() for p in v["name"].split("/")]
        head, rest = parts[0], parts[1:]
        if head == "Color":
            tokens["color"]["-".join(slug(p) for p in rest)] = hexcolor(val)
        elif head == "Spacing":
            tokens["spacing"][slug(rest[0])] = val
        elif head == "Font Family":
            tokens["font"][slug(rest[0])] = val
        elif head == "Font Weight":
            tokens["weight"][slug(rest[0])] = WEIGHTS[slug(rest[0])]
        elif head in ("Desktop", "Mobile"):
            m, kind = head.lower(), rest[0]
            if kind in ("Headlines", "Sub Headings", "Body"):
                tokens["size"][m][slug(rest[1])] = val
            elif kind == "Line Height":
                tokens["lineHeight"][m][slug(rest[1])] = val
            elif kind == "Letter Spacing":
                tokens["letterSpacing"][m][slug(rest[1])] = round(val, 3)
        # Desktop/Typography is an unused string value; skipped.
    tokens["notes"] = notes = [
        "Source is a Figma variables export with a single mode (%s); no dark theme." % d["modes"][mode],
        "Mobile breakpoint assumed at max-width %dpx; the export defines none." % MOBILE_MAX,
        "Missing from export: border radii, shadows, breakpoints, container widths, motion.",
        "Line-height and letter-spacing tokens use t-shirt sizes and are not linked to a type-scale step in the export; confirm the pairing before use.",
        "Font sizes are fractional-rounded values from the export (e.g. 63, 47); used as given.",
    ]
    out = pathlib.Path(out); out.mkdir(parents=True, exist_ok=True)
    json.dump(tokens, open(out / "design-tokens.json", "w"), indent=2)

    css = ["/* Generated by scripts/normalize_design_system.py. Do not edit by hand. */", ":root {"]
    for k, v in tokens["color"].items(): css.append(f"  --site-color-{k}: {v};")
    for k, v in tokens["spacing"].items(): css.append(f"  --site-space-{k}: {v}px;")
    for k, v in tokens["font"].items(): css.append(f"  --site-font-{k}: \"{v.replace('dm-sans','DM Sans').replace('inter','Inter')}\", system-ui, sans-serif;")
    for k, v in tokens["weight"].items(): css.append(f"  --site-weight-{k}: {v};")
    for k, v in tokens["size"]["desktop"].items(): css.append(f"  --site-text-{k}: {v}px;")
    for m in ("desktop", "mobile"):
        for k, v in tokens["lineHeight"][m].items(): css.append(f"  --site-lh-{m}-{k}: {v}px;")
        for k, v in tokens["letterSpacing"][m].items(): css.append(f"  --site-ls-{m}-{k}: {v}px;")
    css += ["}", "", f"@media (max-width: {MOBILE_MAX}px) {{", "  :root {"]
    for k, v in tokens["size"]["mobile"].items(): css.append(f"    --site-text-{k}: {v}px;")
    css += ["  }", "}", ""]
    (out / "site-tokens.css").write_text("\n".join(css))
    print("colors", len(tokens["color"]), "| sizes", len(tokens["size"]["desktop"]), "| spacing", len(tokens["spacing"]))

main(sys.argv[1], sys.argv[2])
